# Generated by Django 3.2 on 2025-02-10 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100, verbose_name='資産名')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='価格')),
                ('asset_type', models.CharField(max_length=50, verbose_name='種類')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('buying_date', models.DateField(verbose_name='購入日')),
            ],
        ),
    ]
